config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

	  devise_for :users
	  get 'pages/index'

	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

		root to: "hotels#index"

		resources :hotels
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    # current_user.locale
    # request.env["HTTP_ACCEPT_LANGUAGE"]
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

	before_action :set_hotel, only: %i[show edit update destroy]

	def index # GET /hotels
		@hotels = Hotel.all
	end

	def show # GET /hotels/:id
		@hotel = Hotel.find(params[:id])
	end

	def new # GET /hotels/new
		@hotel = Hotel.new
	end

	def create # POST /hotels
		@hotel = Hotel.new(hotel_params)
		
		if @hotel.save
			redirect_to hotels_path
		else
      render 'new'
    end
	end

	def edit # GET /hotels/:id/edit
	end

	def update # PATCH /hotels/:id
		@hotel.update(hotel_params)

		if @hotel.save
      redirect_to hotels_path
    else
      render 'edit'
    end
	end

	def destroy # DELETE /hotels/:id
		@hotel.destroy
    redirect_to hotels_path
	end

	private

	def set_hotel
		@hotel = Hotel.find(params[:id])
	end

	def hotel_params
		params.require(:hotel).permit(:name, :country_code, :description)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hotels/edit.html.erb
<h1>Edit a Hotel</h1>

<h3>Edit the details here:</h3>

<div>
  <%= form_for(@hotel) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :country_code %>
    <%= f.text_field :country_code %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit %>
  <% end %>
</div>

app/views/hotels/index.html.erb
<div class="container">
	<h1>Hotels</h1>

	<h3>View all of our hotel properties</h3>

	<div class="body">	
	  <ul>
			<% @hotels.each do |hotel| %>
				<li> 
					<%= hotel.name %> 
					<%= link_to "View", hotel_path(hotel) %>
					<%= link_to "Remove Hotel", hotel_path(hotel), method: :delete %>
				</li>
			<% end %>
		</ul>
		
		<%= link_to new_hotel_path do  %>
				<button type="button" class="btn btn-primary">Add a Hotel</button>
		<% end %>
	</div>

	<div>
		<h6>
		<%= link_to "Signup", new_user_registration_path %>
		</h6>

		<h6>
		<%= link_to "Sign-in", new_user_session_path %>
		</h6>
	</div>
</div>

app/views/hotels/new.html.erb
<h1>Create a new Hotel</h1>

<h3>Please, fill in the details, below:</h3>

<div>
	<%= form_for(@hotel) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :country_code %>
		<%= f.text_field :country_code %>

		<%= f.label :description %>
		<%= f.text_field :description %>

		<%= f.submit %>
	<% end %>
</div>

app/views/hotels/show.html.erb
<div class="container">
	<h1><%= @hotel.name %></h1>	

	<h4>Country</h4>
	<p><%= @hotel.country_code %></p>

	<h4>Description</h4>
	<p><%= @hotel.description %></p>

	<!-- REFERENCE locales == it_IT, es_US, en_UK -->

	<%= content_tag :li do %>
	  <%= link_to 'Description in Italian', locale: :it_IT %>
	<% end unless current_page?(locale: :ja) %>

	<%= content_tag :li do %>
	  <%= link_to 'Description in Spanish', locale: :es_US %>
	<% end unless current_page?(locale: :es_US) %>

	<%= content_tag :li do %>
	  <%= link_to 'Description in English', locale: :en_UK %>
	<% end unless current_page?(locale: :en_UK) %>

	<div>
		<%= link_to "edit", edit_hotel_path %>
	</div>

	<div>
		<%= link_to "back to all hotels", hotels_path %>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workdir</title>
    <%#= csrf_meta_tags %>
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>